version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDatabase
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3002:3002'
    depends_on: 
      - mongo
    networks:
      - my_app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge

volumes:
  mongo-data: